### ISSUE TITLE
Clicking the "Overlay" gear errors out

### ISSUE THREAD

**Issue by Drowbe** [Aedif/TokenVariants#140]
In the Effects Settings, clicking the overlay gear to configure the overlay throws an error (see screenshot). The overlay window does not open. Error:

effectMappingForm.js:324 Uncaught (in promise) TypeError: $parcel$interopDefault(...) is not a constructor
    at y._onOverlayConfigClick (effectMappingForm.js:324:5)
    at HTMLElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

Running Foundry V11.308 and module version 4.56.3.  Let me know if you need any other info.

-- Thomas 

![Screenshot 2023-09-21 at 2 46 13 PM](https://github.com/Aedif/TokenVariants/assets/140648353/c88c06da-0849-4e02-b9ef-644eb017b3c9)

**Comment by Aedif** [comment]
Update to 4.56.4. Should be resolved

**Comment by Drowbe** [comment]
Tried to update... says i have latest. I grabbed the 4.56.4 module.json from your repo and installed that way... but it still says version "4.56.3" -- checked the json file at the version number there and it says 4.56.3 instead of 4.56.4. Guessing you forgot to update the version number? Screenshot below was from the file in "TokenVariants/releases/tag/4.56.4"

![image](https://github.com/Aedif/TokenVariants/assets/140648353/a78343ab-2d68-48a2-9d51-28dc6a2784a3)

**Comment by Drowbe** [comment]
Looks like the path to the zip points to 5.56.3 too.

**Comment by Aedif** [comment]
Ah, I recently changed the structure of the repo and the version didn't get updated in all the right places. 
There are 2 module.json files at the moment. (https://github.com/Aedif/TokenVariants/blob/master/module.json is the legacy one and that's the one that was updated instead of the newer one)

Anyway, both of them should be updated now.

**Comment by Drowbe** [comment]
The fix seems to work! Thank you! Now I need to figure out how to overlay an image over an "unconscious" player without changing their token. (I am coding something for saving throws).  As always, thanks for the incredible work!
